silver-sat/Avionics_Software

- Examples for Programming Workshop/fibo.py
Fibonacci series example for programming workshop
> Fibonnaci series example

- Examples for Programming Workshop/divisors.py
Example for Programming Skills Workshop
> Divisors of a number

- AvionicsTesting1/fram_test_prototype.py
Prototype FRAM test in Python. Note: this is not the FRAM device planned for SilverSat.
> Prototype FRAM test in Python

- AvionicsTesting1/fram_test_prototype/fram_test_prototype.ino
> Arduino FRAM test prototype

- AvionicsTesting1/fram_test_prototype/fram_test_prototype.ino
Change integer data types to fix bug on Arduino UNO
> Fix for Arduino UNO

- AvionicsTesting1/fram_test_prototype.py
> Progress display and time enhancements

- AvionicsTesting1/SilverSat_Bus_Switch_Mock/examples/test_Bus_Switch_mock/test_Bus_Switch_mock.ino
- AvionicsTesting1/SilverSat_Bus_Switch_Mock/src/SilverSat_Bus_Switch_mock.cpp
- AvionicsTesting1/SilverSat_Bus_Switch_Mock/src/SilverSat_Bus_Switch_mock.h
Additional improvements for #33
> Improve consistency

- AvionicsTesting1/SilverSat_MPU6050_Mock/examples/test_MPU6050_mock/test_MPU6050_mock.ino
- AvionicsTesting1/SilverSat_MPU6050_Mock/src/SilverSat_MPU6050_mock.h
> Improve documentation

- AvionicsTesting1/SilverSat_SAMD21_Mock/examples/Test_SAMD21_Mock/Test_SAMD21_mock.ino
- AvionicsTesting1/SilverSat_SAMD21_Mock/library.properties
- AvionicsTesting1/SilverSat_SAMD21_Mock/src/SilverSat_SAMD21_mock.cpp
- AvionicsTesting1/SilverSat_SAMD21_Mock/src/SilverSat_SAMD21_mock.h
> Implement mock SAMD21

- AvionicsTesting1/SilverSat_I2C_Mock/examples/SilverSat_I2C_Mock/test_SilverSat_I2C_mock.ino
- AvionicsTesting1/SilverSat_I2C_Mock/library.properties
- AvionicsTesting1/SilverSat_I2C_Mock/src/SilverSat_I2C_mock.cpp
- AvionicsTesting1/SilverSat_I2C_Mock/src/SilverSat_I2C_mock.h
> Initial implementation

- AvionicsTesting1/Test_Avionics_Board_Mock/Test_Avionics_Board_IMU_Mock.cpp
- AvionicsTesting1/Test_Avionics_Board_Mock/Test_Avionics_Board_Mock.ino
> Correct operator evaluation order

- AvionicsTesting1/Test_Avionics_Board_Mock/Test_Avionics_Board_External_RTC_Mock.cpp
- AvionicsTesting1/Test_Avionics_Board_Mock/Test_Avionics_Board_Mock.h
- AvionicsTesting1/Test_Avionics_Board_Mock/Test_Avionics_Board_Mock.ino
> Integrated external RTC in mock board test

- AvionicsTesting1/SilverSat_FRAM_Mock/library.properties
- AvionicsTesting1/SilverSat_I2C_Mock/library.properties
- AvionicsTesting1/SilverSat_IMU_Mock/library.properties
- AvionicsTesting1/SilverSat_Watchdog_Mock/library.properties
> Update library categories for mock interfaces

- AvionicsTesting2/test_watchdog hardware/test_watchdog_hardware.cpp
- AvionicsTesting2/test_watchdog hardware/test_watchdog_hardware.h
- AvionicsTesting2/test_watchdog hardware/test_watchdog_hardware.ino
> Implement watchdog hardware test

- AvionicsTesting3/test_beacon/test_beacon.ino
- AvionicsTesting3/test_process_loop/beacon.cpp
- AvionicsTesting3/test_process_loop/beacon.h
- AvionicsTesting3/test_process_loop/mock_radio_board.cpp
- AvionicsTesting3/test_process_loop/mock_radio_board.h
- AvionicsTesting3/test_process_loop/test_process_loop.ino
> Beacon-structure-implementation

- AvionicsTesting3/test_command/command.cpp
- AvionicsTesting3/test_command/command.h
- AvionicsTesting3/test_command/test_command.ino
> Implement command structure

- AvionicsTesting3/test_command/test_command.ino
- AvionicsTesting3/test_process_loop/Command.cpp
- AvionicsTesting3/test_process_loop/Command.h
- AvionicsTesting3/test_process_loop/mock_radio_board.cpp
- AvionicsTesting3/test_process_loop/mock_radio_board.h
- AvionicsTesting3/test_process_loop/test_process_loop.ino
> Activate realtime clock

- AvionicsTesting3/test_process_loop/test_process_loop.ino
> Closes #85

- AvionicsTesting3/test_process_loop/Message.cpp
- AvionicsTesting3/test_process_loop/Message.h
> Create Message class

- AvionicsTesting3/test_process_loop/AvionicsBoard.cpp
- AvionicsTesting3/test_process_loop/AvionicsBoard.h
- AvionicsTesting3/test_process_loop/beacon.cpp
- AvionicsTesting3/test_process_loop/beacon.h
- AvionicsTesting3/test_process_loop/mock_radio_board.cpp
- AvionicsTesting3/test_process_loop/mock_radio_board.h
> Update beacon format

- AvionicsTesting2/test_imu_non_crit_i2c/test_imu_non_crit_i2c.ino
- AvionicsTesting3/test_process_loop/AvionicsBoard.cpp
- AvionicsTesting3/test_process_loop/AvionicsBoard.h
- AvionicsTesting3/test_process_loop/ExternalRTC.cpp
- AvionicsTesting3/test_process_loop/ExternalRTC.h
- AvionicsTesting3/test_process_loop/IMU.cpp
- AvionicsTesting3/test_process_loop/IMU.h
- AvionicsTesting3/test_process_loop/Watchdog.cpp
- AvionicsTesting3/test_process_loop/Watchdog.h
- AvionicsTesting3/test_process_loop/board_configuration.h
- AvionicsTesting3/test_process_loop/test_process_loop.ino
> Implement-non-crit-I2C

- AvionicsTesting3/test_process_loop/AvionicsBoard.cpp
- AvionicsTesting3/test_process_loop/AvionicsBoard.h
- AvionicsTesting3/test_process_loop/Command.cpp
- AvionicsTesting3/test_process_loop/Command.h
- AvionicsTesting3/test_process_loop/CommandFactory.cpp
- AvionicsTesting3/test_process_loop/ExternalRTC.cpp
- AvionicsTesting3/test_process_loop/ExternalRTC.h
- AvionicsTesting3/test_process_loop/test_process_loop.ino
- AvionicsTesting3/test_time.py
> Improve RTC logic

- AvionicsTesting3/test_process_loop/mock_payload_board.cpp
- AvionicsTesting3/test_process_loop/mock_payload_board.h
- AvionicsTesting3/test_process_loop/test_process_loop.ino
> Verify Payload conflict processing

- AvionicsTesting3/README.md
- AvionicsTesting3/example.py
- AvionicsTesting3/test_beacon.py
- AvionicsTesting3/test_commands.py
- AvionicsTesting3/test_power.py
- AvionicsTesting3/test_process_loop/AvionicsBoard.cpp
- AvionicsTesting3/test_process_loop/AvionicsBoard.h
- AvionicsTesting3/test_process_loop/Command.cpp
- AvionicsTesting3/test_process_loop/Command.h
- AvionicsTesting3/test_process_loop/CommandFactory.cpp
- AvionicsTesting3/test_process_loop/CommandFactory.h
- AvionicsTesting3/test_process_loop/IMU.cpp
- AvionicsTesting3/test_process_loop/Watchdog.h
- AvionicsTesting3/test_process_loop/board_configuration.h
- AvionicsTesting3/test_process_loop/mock_power_board.h
- AvionicsTesting3/test_process_loop/test_process_loop.ino
- AvionicsTesting3/test_time.py
> Reformat documentation

- AvionicsTesting3/helper.py
- AvionicsTesting3/test_process_loop/Beacon.cpp
- AvionicsTesting3/test_process_loop/mock_radio_board.cpp
- AvionicsTesting3/test_process_loop/mock_radio_board.h
> Add command counters

- AvionicsTesting3/test_commands/helper.py
- AvionicsTesting3/test_process_loop/mock_radio_board.cpp
- AvionicsTesting3/test_process_loop/mock_radio_board.h
> Implement command sequence numbers

- AvionicsTesting3/test_commands/helper.py
- AvionicsTesting3/test_commands/test_aviation_initialization.py
- AvionicsTesting3/test_commands/test_beacon_sp.py
- AvionicsTesting3/test_commands/test_setup.py
- AvionicsTesting3/test_process_loop/mock_payload_board.cpp
- AvionicsTesting3/test_process_loop/mock_radio_board.cpp
> Add initialization validation

- AvionicsTesting3/test_commands/helper.py
- AvionicsTesting3/test_commands/test_clear_pic_times.py
- AvionicsTesting3/test_process_loop/AvionicsBoard.cpp
- AvionicsTesting3/test_process_loop/AvionicsBoard.h
- AvionicsTesting3/test_process_loop/BuildCommand.cpp
- AvionicsTesting3/test_process_loop/ExecuteCommand.cpp
- AvionicsTesting3/test_process_loop/ExecuteCommand.h
> Add ClearPicTimes command

- AvionicsTesting2/test_external_RTC/DS1337.cpp
- AvionicsTesting2/test_external_RTC/DS1337.h
- AvionicsTesting2/test_external_RTC/test_external_RTC.ino
- AvionicsTesting3/test_process_loop/DS1337.cpp
- AvionicsTesting3/test_process_loop/DS1337.h
- AvionicsTesting3/test_process_loop/ExternalRTC.cpp
- AvionicsTesting3/test_process_loop/ExternalRTC.h
> Implement DS1337

- AvionicsTesting2/test_FRAM/CY15B256J.cpp
- AvionicsTesting2/test_FRAM/CY15B256J.h
- AvionicsTesting2/test_FRAM/test_FRAM.ino
- AvionicsTesting3/test_process_loop/AvionicsBoard.h
- AvionicsTesting3/test_process_loop/CY15B256J.cpp
- AvionicsTesting3/test_process_loop/CY15B256J.h
> Implement CY15B256J

- AvionicsTesting3/test_process_loop/mock_radio_board.cpp
- AvionicsTesting3/test_process_loop/mock_radio_board.h
> Add initial message sync

- AvionicsTesting2/test_external_i2c/test_external_i2c.ino
- AvionicsTesting3/test_process_loop/AvionicsBoard.h
- AvionicsTesting3/test_process_loop/EPS_I.cpp
- AvionicsTesting3/test_process_loop/EPS_I.h
- AvionicsTesting3/test_process_loop/ExecuteCommand.cpp
- AvionicsTesting3/test_process_loop/mock_power_board.cpp
- AvionicsTesting3/test_process_loop/mock_radio_board.cpp
> EPS-driver

- AvionicsTesting3/test_commands/test_beacon_sp.py
- AvionicsTesting3/test_commands/test_twee_slee.py
- AvionicsTesting3/test_process_loop/AvionicsBoard.cpp
- AvionicsTesting3/test_process_loop/AvionicsBoard.h
- AvionicsTesting3/test_process_loop/BuildCommand.cpp
- AvionicsTesting3/test_process_loop/CY15B256J.cpp
- AvionicsTesting3/test_process_loop/CollectCommand.cpp
- AvionicsTesting3/test_process_loop/DS1337.cpp
- AvionicsTesting3/test_process_loop/EPS_I.h
- AvionicsTesting3/test_process_loop/ExecuteCommand.cpp
- AvionicsTesting3/test_process_loop/ExecuteCommand.h
- AvionicsTesting3/test_process_loop/ExternalRTC.cpp
- AvionicsTesting3/test_process_loop/ExternalWatchdog.cpp
- AvionicsTesting3/test_process_loop/ExternalWatchdog.h
- AvionicsTesting3/test_process_loop/IMU.cpp
- AvionicsTesting3/test_process_loop/board_configuration.h
- AvionicsTesting3/test_process_loop/mock_payload_board.cpp
- AvionicsTesting3/test_process_loop/mock_payload_board.h
- AvionicsTesting3/test_process_loop/mock_power_board.cpp
- AvionicsTesting3/test_process_loop/mock_power_board.h
- AvionicsTesting3/test_process_loop/mock_radio_board.cpp
- AvionicsTesting3/test_process_loop/mock_radio_board.h
- AvionicsTesting3/test_process_loop/test_process_loop.ino
> Board-testing

- FlatSat/avionics_loop/AvionicsBoard.cpp
- FlatSat/avionics_loop/AvionicsBoard.h
- FlatSat/avionics_loop/Beacon.h
- FlatSat/avionics_loop/RadioBoard.cpp
> Fix Beacon

- FlatSat/avionics_loop/Commands.cpp
- FlatSat/avionics_loop/PayloadBoard.cpp
- FlatSat/avionics_loop/PayloadBoard.h
- FlatSat/payload_simulator/payload_simulator.py
- FlatSat/payload_simulator/payload_simulator_test/payload_simulator_test.ino
> Add payload startup and shutdown delays

- FlatSat/avionics_loop/AvionicsBoard.cpp
- FlatSat/avionics_loop/AvionicsBoard.h
- FlatSat/avionics_loop/PowerBoard.cpp
> Enable busswitch permanently

- FlatSat/avionics_loop/AvionicsBoard.cpp
> Clear Picture Queue on UnsetClock

- AvionicsTesting2/test_FRAM_persistence/CY15B256J.cpp
- AvionicsTesting2/test_FRAM_persistence/CY15B256J.h
- AvionicsTesting2/test_FRAM_persistence/test_FRAM_persistence.ino
> Add FRAM persistence test

- FlatSat/avionics_loop/Beacon.h
- FlatSat/avionics_loop/PowerBoard.cpp
- FlatSat/avionics_loop/PowerBoard.h
- FlatSat/silver_sat_cli/sscli.py
> Power-beacon

- FlatSat/avionics_loop/Beacon.h
> Update Avionics beacon

- FlatSat/avionics_loop/Antenna.cpp
- FlatSat/avionics_loop/PowerBoard.cpp
- FlatSat/avionics_loop/RadioBoard.cpp
- FlatSat/avionics_loop/RadioBoard.h
- FlatSat/test_avionics/utility.py
Minor fixes to enable FlatSat tests
> Enable FlatSat testing

- FlatSat/avionics_loop/CY15B256J.cpp
- FlatSat/avionics_loop/DS1337.cpp
- FlatSat/avionics_loop/EPS_I.cpp
> Scan for I2C devices on startup

- FlatSat/avionics_loop/Beacon.h
- FlatSat/avionics_loop/PayloadBoard.cpp
- FlatSat/payload_simulator/payload_simulator.py
- FlatSat/payload_simulator/test_payload_beacons.py
- FlatSat/test_avionics/utility.py
> Implement Payload beacon updates

- FlatSat/README.md
- FlatSat/avionics_loop/AvionicsBoard.cpp
- FlatSat/avionics_loop/avionics_loop.ino
- FlatSat/test_avionics/utility.py
> Remove internal watchdog

- FlatSat/avionics_loop/CY15B256J.h
- FlatSat/avionics_loop/DS1337.cpp
- FlatSat/avionics_loop/DS1337.h
- FlatSat/avionics_loop/EPS_I.cpp
- FlatSat/avionics_loop/EPS_I.h
- FlatSat/avionics_loop/PowerBoard.cpp
> Add LUP 5V data to GetPower

- FlatSat/avionics_loop/PayloadBoard.cpp
- FlatSat/avionics_loop/PayloadBoard.h
- FlatSat/payload_simulator/payload_simulator.py
> Update Payload shutdown processing

- FlatSat/avionics_loop/avionics_loop.ino
> Enable boot with no serial log port

- Flight/avionics/AvionicsBoard.cpp
- Flight/avionics/AvionicsBoard.h
- Flight/avionics/CommandFactory.cpp
- Flight/avionics/Commands.cpp
- Flight/avionics/RadioBoard.cpp
- Flight/avionics/RadioBoard.h
- Flight/avionics/avionics.ino
- Flight/avionics/avionics_constants.h
- Flight/avionics/log_utility.cpp
This pull request refactors log messages, removes TODOs, and adds a beacon timeout feature.
> Refactor log messages and remove TODOs, add beacon timeout

- Flight/avionics/Antenna.cpp
- Flight/avionics/Message.cpp
- Flight/avionics/Message.h
- Flight/avionics/avionics.ino
Change enum name and update comments
> Change enum name

- Flight/avionics/IMU.h
- Flight/avionics/RadioBoard.cpp
- Flight/avionics/avionics.ino
- Flight/test_satellite/common.py
> Serial monitor speed fix

- Flight/avionics/Antenna.cpp
- Flight/avionics/AvionicsBoard.cpp
- Flight/avionics/avionics.ino
> 80-second-antenna-delay

- Flight/avionics/Antenna.h
- Flight/avionics/IMU.h
- Flight/avionics/PayloadBoard.cpp
- Flight/avionics/PowerBoard.cpp
> Restore_payload_voltage_min

- Flight/avionics/PowerBoard.cpp
> initial battery voltage in log

- Flight/avionics/IMU.h
> changed imu calibration

- Flight/avionics/Antenna.h
- Flight/avionics/EPS_I.cpp
- Flight/avionics/EPS_I.h
- Flight/avionics/PowerBoard.cpp
> turn on 5v turn 3.3v LUPS

- Flight/avionics/PayloadQueue.cpp
- Flight/avionics/RadioBoard.cpp
- Flight/avionics/RadioBoard.h
- Flight/avionics/avionics.ino
- Flight/avionics/avionics_constants.h
> Working implementation

- Flight/avionics/CommandWarehouse.cpp
- Flight/avionics/CommandWarehouse.h
- Flight/avionics/Commands.cpp
- Flight/avionics/Commands.h
- Flight/test_satellite/test_commands.py
> Implement LogArguments command

- Flight/avionics/AvionicsBoard.cpp
- Flight/avionics/AvionicsBoard.h
- Flight/avionics/IMU.cpp
- Flight/avionics/IMU.h
- Flight/avionics/avionics.ino
> Add IMU test

- Flight/avionics/Antenna.cpp
- Flight/avionics/Antenna.h
- Flight/avionics/AvionicsBoard.cpp
- Flight/avionics/PowerBoard.cpp
- Flight/avionics/avionics.ino
> Add antenna test

- Flight/avionics/avionics.ino
This pull request includes the initial implementation of the code and a payload test. The initial implementation sets up the necessary components for testing, while the payload test specifically focuses on testing the payload functionality.
> Add initial implementation and payload test

- Flight/avionics/Antenna.h
- Flight/avionics/CommandProcessor.cpp
- Flight/avionics/Message.h
- Flight/avionics/RadioBoard.cpp
- Flight/avionics/RadioBoard.h
- Flight/avionics/avionics.ino
> Add-radio-test

- Flight/avionics/Antenna.cpp
- Flight/avionics/Antenna.h
- Flight/avionics/avionics.ino
> Fix antenna deployment bugs

- Flight/avionics/CommandProcessor.cpp
- Flight/avionics/CommandProcessor.h
- Flight/avionics/CommandWarehouse.cpp
- Flight/avionics/CommandWarehouse.h
- Flight/avionics/Commands.cpp
- Flight/avionics/Commands.h
- Flight/avionics/Message.h
- Flight/avionics/RadioBoard.cpp
- Flight/avionics/avionics_constants.h
- Flight/test_satellite/common.py
- Flight/test_satellite/test_commands.py
Refactor command processing and merge Radio Check branch
> Enhance-command-processing

- Flight/avionics/CommandProcessor.cpp
> Improve error message

- Flight/avionics/Antenna.cpp
- Flight/avionics/Antenna.h
- Flight/avionics/AvionicsBoard.cpp
- Flight/avionics/CommandProcessor.cpp
- Flight/avionics/CommandProcessor.h
- Flight/avionics/Commands.cpp
- Flight/avionics/EPS_I.cpp
- Flight/avionics/RadioBoard.cpp
- Flight/avionics/RadioBoard.h
- Flight/avionics/avionics.ino
- Flight/test_satellite/common.py
Refactor and tune code based on FlatSat tests
> FlatSat-testing

- Flight/avionics/avionics.ino
> Enhance avionics initialization with error handling and logging
